name: onos
version: 1.7.1
summary: ONOS SDN
description: |
  The Open Network Operating System (ONOS) is a software defined networking
  (SDN) OS for service providers that has scalability, high availability, high
  performance and abstractions to make it easy to create apps and services.
grade: stable
confinement: strict

apps:
  onos:
    command: onos
    plugs:
      - network
  form-cluster:
    command: form-cluster
    plugs:
      - network
  service:
    command: service
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  jre:
    plugin: nil
    stage-packages: [default-jre-headless]
  wrappers:
    plugin: dump
    source: wrappers/
    stage-packages: [rsync]
  onos:
    #source: https://gerrit.onosproject.org/onos.git
    source: https://github.com/opennetworkinglab/onos/archive/1.7.1.tar.gz
    plugin: x-onos-buck
    #source: ../tar/onos-1.7.1
    #plugin: dump
    build-packages: [python, default-jdk-headless, zip, unzip]
